// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3489.CommandBasedRobot2.subsystems;
import org.usfirst.frc3489.CommandBasedRobot2.RobotMap;
import org.usfirst.frc3489.CommandBasedRobot2.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
/**
 *
 */
public class Ultra extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    AnalogChannel sensorOut = RobotMap.ultraSensorOut;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public double conversion() {
        double value1 = sensorOut.getAverageVoltage();
        Timer.delay(.01);
        double value2 = sensorOut.getAverageVoltage();
        Timer.delay(.01);
        double value3 = sensorOut.getAverageVoltage();
        Timer.delay(.01);
        double value4 = sensorOut.getAverageVoltage();
        Timer.delay(.01);
        double value5 = sensorOut.getAverageVoltage();
        Timer.delay(.01);
        double value6 = sensorOut.getAverageVoltage();
        Timer.delay(.01);
        double value7 = sensorOut.getAverageVoltage();
        Timer.delay(.01);
        double value8 = sensorOut.getAverageVoltage();
        Timer.delay(.01);
        double value9 = sensorOut.getAverageVoltage();
        Timer.delay(.01);
        double value10 = sensorOut.getAverageVoltage();
        Timer.delay(.01);
        double ultaverage = (value1 + value2 + value3 + value4 + value5 + value6 + value7 + value8 + value9 + value10) / 10;
        System.out.println("UltValue1 - " + value1);
        System.out.println("UltValue2 - " + value2);
        System.out.println("UltValue3 - " + value3);
        System.out.println("UltValue4 - " + value4);
        System.out.println("UltValue5 - " + value5);
        System.out.println("UltValue6 - " + value6);
        System.out.println("UltValue7 - " + value7);
        System.out.println("UltValue8 - " + value8);
        System.out.println("UltValue9 - " + value9);
        System.out.println("UltValue10 - " + value10);
        //SmartDashboard.putNumber("Berst Avererg - ", ultaverage);
        double feet = ultaverage * 8.5179;
        return feet;   
   }
    
      public void turnoff() {
       sensorOut.free();
   }
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}
